[workspace]
members = ["cli", "common", "config", "db", "test_utils"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
chrono = "0.4.31"
dialoguer = "0.11.0"
diesel = { version = "2.1.4", features = [
    "chrono",
    "returning_clauses_for_sqlite_3_35",
    "sqlite",
] }
diesel_migrations = "2.1.0"
dirs = "5.0.1"
serde = { version = "1.0.193", features = ["derive"] }
tempfile = "3.8.1"
test-case = "3.3.1"
thiserror = "1.0.52"
toml = "0.8.8"

# Internal
hms-common = { path = "common" }
hms-config = { path = "config" }
hms-db = { path = "db" }
hms-test_utils = { path = "test_utils" }
