[workspace]
resolver = "2"
members = [
    "cli",
    "config",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = "1.0.193"
serde_derive = "1.0.193"
hms-config = { path = "config" }
