[package]
authors.workspace    = true
description          = "Common lib for Hold my Snip!"
edition.workspace    = true
license.workspace    = true
name                 = "hms-common"
repository.workspace = true
version.workspace    = true

[dependencies]
dirs.workspace = true
