CREATE TABLE snips (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    alias VARCHAR(50) NOT NULL UNIQUE CHECK(length(alias) <= 50),
    value VARCHAR NOT NULL,
    access_count INTEGER NOT NULL DEFAULT 0,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_access DATETIME
);
