name: PR workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Check-Build-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: false
        components: rustfmt

    - name: Check formatting
      run: cargo +nightly fmt -- --check -v

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
